### ISSUE TITLE
Alignment of Featured Teas

### ISSUE THREAD

**Issue by kfdesign** [Gadget-Geek/TeaCozy#1]
https://github.com/Gadget-Geek/TeaCozy/blob/a8684d93997e6b70c410119a29d392d5c7c1ca76/index.html#L25

While I’m sure it is not the only solution, I put two child DIVs inside the main “Featured” parent. The reason I did this is because I could not get the spacing, horizontal and vertical, between all 5 of the teas to work properly.
I found that if I split the teas into two DIVs (top and bottom) I was able to control the spacing.

**Comment by Gadget-Geek** [comment]
Thanks Kevin for the advice! Turns out I just had to set `flex-wrap: wrap` inside the `.Featured` and `.tea-list` selectors separately. See my repo now for the exact details of how I did this.
