### ISSUE TITLE
Add mobile resizing

### ISSUE THREAD

**Issue by sangjunp4rk** [Gadget-Geek/TeaCozy#5]
In the future, try to incorporate mobile resizing. Though it may seem tedious, it is an incredibly important concept since screen sizes vary tremendously today and it’s important that you website looks exactly as you design it to.

**Comment by Gadget-Geek** [comment]
Hi Sang, isn't mobile resizing a topic in the next unit? If so, then I will try to inject what I learn there into the capstone.
